### PR TITLE
Adjust boot settings for Connect 4

### PR DESCRIPTION
**Pull request by linosanfilippo-kunbus**
Correct write protect PIN and configure tx line for debug UART.

### CODE REVIEW

**Comment by nbuchwitz** [comment]
Please note that changes need to be applied to all product variants (100376 - 385)

**Comment by iluminat23** [comment]
> Please note that changes need to be applied to all product variants (100376 - 385)

Yes, this is known. For the draft we just use one file. This makes reviews easier.

**Comment by iluminat23** [comment]
Looks good, Add the other devices and we are ready for the full review!

**Comment by nbuchwitz** [comment]
There are a few variants missing, which are about to be introduced with #15

**Review by iluminat23 — APPROVED** [review]

**Pull request merged**
