### PR TITLE
Add missing RevPi Connect 4 devices

### PR DESCRIPTION
**Pull request by nbuchwitz**
Add missing Connect 4 devices

### CODE REVIEW

**Comment by iluminat23** [comment]
I would schedule this after https://github.com/RevolutionPi/revpi-hat-data/pull/14, is this ok?

**Comment by nbuchwitz** [comment]
Works for me. I'll force push the changes as soon they are reviewed.

**Comment by iluminat23** [comment]
@linosanfilippo-kunbus and @nbuchwitz please do rock paper scissors who goes first. The loser needs to pick-up the changes from the other one.

**Comment by nbuchwitz** [comment]
@iluminat23, @linosanfilippo-kunbus and I played and decided to merge this one first. Are there any objections? If not not feel free to approve.

**Review by linosanfilippo-kunbus — APPROVED** [review]

**Pull request merged**
